server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://eureka8101.com:8101/eureka/,http://eureka8101.com:8100/eureka/
  instance:
    instance-id: uaa-provider-9100
spring:
  application:
    name: uaa-provider