server:
  port: 8101

eureka:
  instance:
    hostname: eureka8101.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8100.com:8100/eureka/