spring:
  application:
    name: uaa-oauth2-jwt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/octopus-pay?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root123456
server:
  port: 3100
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka8101.com:8101/eureka/,http://eureka8101.com:8100/eureka/
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml