server:
  port: 8100

eureka:
  instance:
    hostname: eureka8100.com
  server:
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8101.com:8101/eureka/
