server:
  port: 5100
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tangyinbo/spring-cloud-config
          username: tangyinboit@163.com
          password: tangxuhua_520
      name: config-center
  application:
    name: config-center
eureka:
  client:
    service-url:
      defaultZone: http://eureka8101.com:8101/eureka/,http://eureka8101.com:8100/eureka/
  instance:
    instance-id: config-center